CREATE DATABASE ideo;

CREATE TABLE Usuarios (
    UserID INT PRIMARY KEY ,
    UserName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
